server:
  port: 9002

spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db0?serverTimezone=UTC
        username: root
        password: wanghongyu
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
        username: root
        password: wanghongyu
    sharding:
      default-database-strategy:
        inline:
          sharding-column: age
          algorithm-expression: ds$->{age%2}
      tables:
        tab_user:
          actual-data-nodes: ds$->{0..1}.tab_user$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id%2}