server:
  port: 9003
spring:
  shardingsphere:
    datasource:
      names: master0,slave0
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?serverTimezone=UTC
        username: root
        password: wanghongyu
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave?serverTimezone=UTC
        username: root
        password: wanghongyu
    sharding:
      tables:
        tab_user:
          actual-data-nodes: master0.tab_user$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id % 2}
      master-slave-rules:
        master0:
          master-data-source-name: master0
          slave-data-source-names: slave0
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
    props:
      sql:
        show: true